---
title: "OPLA POLA Media Analysis"
author: "Felix Westcott"
date: "22/02/2022"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(ggplot2)
library(readxl)
library(xlsx)
library(dplyr)
library(ggpubr)
library(ggsci)
library(rstatix)
library (cowplot)

setwd('C:/Users/fwestcott/OneDrive - Nexus365/Desktop/Results/OPLA-vs-POLA')

All_Data <- read_excel("OPLA POLA Media analysis.xlsx", sheet = 3)

All_Data$"Treatment Length (days)" <- as.factor(All_Data$"Treatment Length (days)")
All_Data$"Media" <- factor(All_Data$"Media", levels = c("Control", "800uM OPLA", "800uM POLA"))

```


``` {r Graphs}

ggline(All_Data, x = "Treatment Length (days)", y= "Media 3-OHB (umol/g of protein)", shape = "Media", color = "Media", add = "mean_se", palette = "npg") +
theme(axis.text.x = element_text(color = "grey20", size = 12),
axis.text.y = element_text(color = "grey20", size = 12),
axis.title.x = element_text(color = "grey20", size = 14),
axis.title.y = element_text(color = "grey20", size = 14),
legend.title = element_text(color = "grey20", size = 12),
legend.text = element_text(color = "grey20", size = 10))
ggsave('C:/Users/fwestcott/OneDrive - Nexus365/Desktop/Results/OPLA-vs-POLA/graphs/3-OHB.png')

ggline(All_Data, x = "Treatment Length (days)", y= "Media TAG (umol/g of protein)", shape = "Media", color = "Media", add = "mean_se", palette = "npg") +
theme(axis.text.x = element_text(color = "grey20", size = 12),
axis.text.y = element_text(color = "grey20", size = 12),
axis.title.x = element_text(color = "grey20", size = 14),
axis.title.y = element_text(color = "grey20", size = 14),
legend.title = element_text(color = "grey20", size = 12),
legend.text = element_text(color = "grey20", size = 10))
ggsave('C:/Users/fwestcott/OneDrive - Nexus365/Desktop/Results/OPLA-vs-POLA/graphs/FrTAG.png')

ggline(All_Data, x = "Treatment Length (days)", y= "Media ApoB (mg/mg of protein)", shape = "Media", color = "Media", add = "mean_se", palette = "npg") +
theme(axis.text.x = element_text(color = "grey20", size = 12),
axis.text.y = element_text(color = "grey20", size = 12),
axis.title.x = element_text(color = "grey20", size = 14),
axis.title.y = element_text(color = "grey20", size = 14),
legend.title = element_text(color = "grey20", size = 12),
legend.text = element_text(color = "grey20", size = 10))
ggsave('C:/Users/fwestcott/OneDrive - Nexus365/Desktop/Results/OPLA-vs-POLA/graphs/FrApoB.png')

ggline(All_Data, x = "Treatment Length (days)", y= "Media Lactate (mmol/g of protein)", shape = "Media", color = "Media", add = "mean_se", palette = "npg") +
theme(axis.text.x = element_text(color = "grey20", size = 12),
axis.text.y = element_text(color = "grey20", size = 12),
axis.title.x = element_text(color = "grey20", size = 14),
axis.title.y = element_text(color = "grey20", size = 14),
legend.title = element_text(color = "grey20", size = 12),
legend.text = element_text(color = "grey20", size = 10))
ggsave('C:/Users/fwestcott/OneDrive - Nexus365/Desktop/Results/OPLA-vs-POLA/graphs/Lac.png')

ggline(All_Data, x = "Treatment Length (days)", y= "Media Urea (mmol/g of protein)", shape = "Media", color = "Media", add = "mean_se", palette = "npg") +
theme(axis.text.x = element_text(color = "grey20", size = 12),
axis.text.y = element_text(color = "grey20", size = 12),
axis.title.x = element_text(color = "grey20", size = 14),
axis.title.y = element_text(color = "grey20", size = 14),
legend.title = element_text(color = "grey20", size = 12),
legend.text = element_text(color = "grey20", size = 10))
ggsave('C:/Users/fwestcott/OneDrive - Nexus365/Desktop/Results/OPLA-vs-POLA/graphs/Urea.png')

ggline(All_Data, x = "Treatment Length (days)", y= "TAG:ApoB Ratio", shape = "Media", color = "Media", add = "mean_se", palette = "npg") +
theme(axis.text.x = element_text(color = "grey20", size = 12),
axis.text.y = element_text(color = "grey20", size = 12),
axis.title.x = element_text(color = "grey20", size = 14),
axis.title.y = element_text(color = "grey20", size = 14),
legend.title = element_text(color = "grey20", size = 12),
legend.text = element_text(color = "grey20", size = 10))
ggsave('C:/Users/fwestcott/OneDrive - Nexus365/Desktop/Results/OPLA-vs-POLA/graphs/TAG_ApoB Ratio.png')

ggline(All_Data, x = "Treatment Length (days)", y= "Fatty acid uptake (%)", color = "Media", add = "mean_se", palette = "npg", remove = "Control") +
theme(axis.text.x = element_text(color = "grey20", size = 12),
axis.text.y = element_text(color = "grey20", size = 12),
axis.title.x = element_text(color = "grey20", size = 14),
axis.title.y = element_text(color = "grey20", size = 14),
legend.title = element_text(color = "grey20", size = 12),
legend.text = element_text(color = "grey20", size = 10))
ggsave('C:/Users/fwestcott/OneDrive - Nexus365/Desktop/Results/OPLA-vs-POLA/graphs/FA_Uptake.png')


```
``` {R Stats}
All_Data_Stats <- rename(All_Data, "Time" = "Treatment Length (days)")
All_Data_Stats$"Time" <- as.factor(All_Data_Stats$"Time")
All_Data_Stats$"Media" <- factor(All_Data_Stats$"Media", levels = c("Control", "800uM OPLA", "800uM POLA"))

for (i in 8:ncol(All_Data_Stats)) {
   formula <- as.formula(paste(colnames(All_Data_Stats)[i], " ~ Media*Time", sep=""))
   model <- aov(formula, data = All_Data_Stats)

   cat("\n-----\n\n")
   cat(colnames(All_Data_Stats)[i])
   cat("\n")
   print(summary(model))
}

```
